#!/bin/bash

THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function link() {
    rm -rf ~/.$1
    ln -s $THISDIR/$2 ~/.$1
}

git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si --noconfirm
rm -rf yay

mkdir -p ~/.config/{sx,i3,i3status,kitty,rofi}

link gitignore         gitignore
link gemrc             gemrc
link eslintrc          eslintrc
link tmux.conf         tmux.conf
link gitconfig         archlinux/gitconfig
link bashrc            archlinux/bashrc
link Xresources        archlinux/Xresources
link config/sx         archlinux/config/sx
link config/kitty      archlinux/config/kitty
link config/i3         archlinux/config/i3
link config/i3status   archlinux/config/i3status
link config/rofi       archlinux/config/rofi
link config/picom.conf archlinux/config/picom.conf

unset THISDIR

echo
echo Done.
echo
