hide-cursor-when-typing = true
padding-x = 16
padding-y = [0, 8]
option-as-alt = 'left'
confirm-before-quit = false

[editor]
program = "vim"
args = []

[window]
width = 600
height = 640
mode = "Windowed"
opacity = 0.75
blur = true
decorations = "Buttonless"

[cursor]
blinking = true
blinking-interval = 530

[fonts]
size = 13

line-height = 1.2

[fonts.regular]
family = "JetBrains Mono"
style = "Normal"
weight = 400

[fonts.bold]
family = "JetBrains Mono"
style = "Normal"
weight = 800

[fonts.italic]
family = "JetBrains Mono"
style = "Italic"
weight = 400

[fonts.bold-italic]
family = "JetBrains Mono"
style = "Italic"
weight = 800

[navigation]
mode = "Plain"

[colors]
cursor = '#00af87'
background = '#171717'
foreground = '#C5C8C6'
# cursor = '#F38BA3'
# tabs = '#443d40'
# tabs-active = '#F38BA3'
# green = '#0BA95B'
# red = '#ED203D'
# blue = '#12B5E5'
# yellow = '#FCBA28'

[platform]
macos.font.size = 13
linux.font.size = 7
