#!/usr/bin/env bash

issue="$(cat /etc/issue)"

if ! [[ $issue =~ "Debian" ]]; then
    printf 'This script is for Debian only.\n'
    exit 1;
fi

# Remove old packages
sudo apt-get remove docker docker-engine docker.io containerd runc

# Allow apt to use a repository over HTTP S
sudo apt-get update
sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

# Get Docker's GPG key
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# Add the Docker repository
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Docker engine
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin

# Verify
sudo docker run hello-world

# Add user to docker group
sudo usermod -aG docker "$USER"
