# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

font_family      MonoLisaCode Light
italic_font      MonoLisaCode Light Italic
bold_font        MonoLisaCode Bold
bold_italic_font MonoLisaCode Bold Italic

font_size 11.0
adjust_line_height 100%
modify_font cell_width 99%

background_opacity 0.97
dynamic_background_opacity yes
