#!/bin/bash

THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function link() {
    rm -rf ~/.$1
    ln -s $THISDIR/$2 ~/.$1
}

mkdir -p ~/.config/{bspwm,panel,sxhkd,kitty}

link gitignore gitignore
link gemrc gemrc
link eslintrc eslintrc
link tmux.conf tmux.conf
link gitconfig archlinux/gitconfig
link bashrc archlinux/bashrc
link Xresources archlinux/Xresources
link xinitrc archlinux/xinitrc
link config/kitty archlinux/config/kitty

link config/bspwm archlinux/config/bspwm
link config/sxhkd archlinux/config/sxhkd
link config/panel archlinux/config/panel

unset THISDIR

echo
echo Done.
echo
