#!/bin/bash

THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function link() {
    rm -rf ~/.$1
    ln -s $THISDIR/$2 ~/.$1
}

mkdir -p ~/.config

link gitignore gitignore
link gemrc gemrc
link eslintrc eslintrc
link tmux.conf tmux.conf
link config/bspwm config/bspwm
link config/sxhkd config/sxhkd
link gitconfig archlinux/gitconfig
link bashrc archlinux/bashrc

unset THISDIR

echo
echo Done.
echo
