brew "alejandra"
brew "bash-language-server"
brew "brotli"
brew "coreutils"
brew "curl"
brew "curl"
brew "direnv"
brew "duf"
brew "elm"
brew "elm-format"
brew "ffmpeg"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "gnupg"
brew "go-task"
brew "helix"
brew "htop"
brew "imagemagick"
brew "jq"
brew "librsvg"
brew "lua-language-server"
brew "luajit"
brew "make"
brew "moreutils"
brew "nodejs"
brew "optipng"
brew "postgresql"
brew "prettier"
brew "python3"
brew "redis"
brew "ripgrep"
brew "semgrep"
brew "shellcheck"
brew "shfmt"
brew "stylua"
brew "svgo"
brew "tmux"
brew "tree"
brew "tree-sitter"
brew "ttyd"
brew "vscode-langservers-extracted"
brew "webp"
brew "wget"
brew "yaml-language-server"
brew "z.lua"
brew "zlib"
brew "zopfli"

brew "delve"
brew "gofumpt"
brew "goimports"
brew "golang"
brew "golangci-lint"
brew "golangci-lint-langserver"
brew "gopls"

cask "1password"
cask "adobe-creative-cloud"
cask "airflow"
cask "blender"
cask "cleanshot"
cask "discord"
cask "dropbox"
cask "element"
cask "figma"
cask "firefox"
cask "ghostty"
cask "google-drive"
cask "kitty"
cask "linear-linear"
cask "monitorcontrol"
cask "rio"
cask "superhuman"
cask "telegram"
cask "visual-studio-code"
cask "whatsapp"

mas "1Password for Safari", id: 1569813296
mas "Compressor", id: 424390742
mas "Icon Slate", id: 439697913
mas "Microsoft Excel", id: 462058435
mas "Microsoft Word", id: 462054704
mas "WhatsApp", id: 310633997
