brew "alejandra"
brew "bash"
brew "bash-completion@2"
brew "bash-language-server"
brew "coreutils"
brew "curl"
brew "direnv"
brew "duf"
brew "elm"
brew "elm-format"
brew "flyctl"
brew "gcc"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "gnu-tar"
brew "gnupg"
brew "htop"
brew "kakoune"
brew "librsvg"
brew "make"
brew "mise"
brew "moreutils"
brew "optipng"
brew "rio-terminal"
brew "tree"
brew "ttyd"
brew "vscode-langservers-extracted"
brew "webp"
brew "wget"
brew "yaml-language-server"
brew "z.lua"
brew "zlib"

brew "go"
brew "gopls"
brew "goimports"
brew "gofumpt"
brew "golangci-lint-langserver"
brew "delve"

cask "ghostty"
cask "kitty"

mas "Compressor", id: 424390742
mas "Icon Slate", id: 439697913
