#!/bin/bash

echo "" >> /etc/apt/sources.list
echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list
echo "deb-src http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list

apt-get update

apt-get -t buster-backports --yes install \
    sudo build-essential pkg-config \
    libtool libtool-bin cmake gettext unzip libncurses-dev libncurses5 \
    curl wget git \
    xorg bspwm sxhkd \
    open-vm-tools open-vm-tools-desktop \
    golang nodejs zopfli brotli \
    rxvt-unicode kitty iceweasel \
    fonts-noto \
    ripgrep

sudo systemctl enable open-vm-tools
sudo systemctl start open-vm-tools

# Neovim
git clone https://github.com/neovim/neovim.git
cd neovim
git checkout stable
make
make install

# Give main user sudo privleges
echo "%sudo ALL=(ALL) NOPASSWD: ALL" | EDITOR="tee -a" /sbin/visudo
/sbin/usermod -a -G sudo christian

reboot
