#!/bin/bash

THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DROPBOX=$HOME/Soft\ Power\ Dropbox/Christian\ Rocha

if [[ -z $XDG_CONFIG_HOME ]]; then
    XDG_CONFIG_HOME="$HOME/.config"
fi
mkdir -p "$XDG_CONFIG_HOME"

function link() {
    rm -rf "${HOME:?}/$1"
    ln -s "$THISDIR/$2" "$HOME/$1"
}

link .gitignore gitignore
link .gemrc gemrc
link .eslintrc eslintrc
link .tmux.conf tmux.conf
link .gitconfig macos/gitconfig
link .bashrc macos/bashrc
link .bash_profile macos/bash_profile
link .grc .grc
link .skhdrc macos/skhdrc
link .config/.floskell.json floskell.json
link .hindent.yaml hindent.yaml
link .config/fish config/fish

# Yabai
YABAI_DIR="$XDG_CONFIG_HOME/yabai"
rm -rf "$YABAI_DIR"
mkdir "$YABAI_DIR"
ln -s "$THISDIR/macos/yabairc" "$XDG_CONFIG_HOME/yabai/yabairc"

# SSH
rm -rf ~/.ssh
ln -s "${DROPBOX}"/System/ssh ~/.ssh
chmod 0700 ~/.ssh
chmod 0600 ~/.ssh/id_rsa*

# AWS Credentials
rm -rf ~/.aws
ln -s "${DROPBOX}"/System/aws ~/.aws
chmod 0700 ~/.aws
chmod 0600 ~/.aws/*

# Kitty
KITTY_DIR="$HOME/.config/kitty"
rm -rf "$KITTY_DIR"
mkdir -p "$KITTY_DIR"
ln -s "$THISDIR/kitty.conf" "$KITTY_DIR/kitty.conf"

# Starship
STARSHIP_FILE="$HOME/.config/starship.toml"
rm -f "$STARSHIP_FILE"
ln -s "$THISDIR/macos/starship.toml" "$STARSHIP_FILE"

# XCode Themes
XCODE_THEMES="$HOME/Library/Developer/Xcode/UserData/FontAndColorThemes"
rm -rf "$XCODE_THEMES"
mkdir -p "$XCODE_THEMES"
ln -s "$THISDIR/xcode/Meowgorithm.dvtcolortheme" "$XCODE_THEMES/Meowgorithm.dvtcolortheme"
ln -s "$HOME/xcode/MeowgorithmMorning.dvtcolortheme" "$XCODE_THEMES/MeowgorithmMorning.dvtcolortheme"

echo
echo Done.
echo
