#!/bin/bash

THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DROPBOX=$HOME/Magic\ Numbers\ Dropbox/Christian\ Rocha

function link() {
    rm -rf ~/$1
    ln -s $THISDIR/$2 ~/$1
}

link .gitignore gitignore
link .gemrc gemrc
link .eslintrc eslintrc
link .zshrc zshrc
link .tmux.conf tmux.conf
link .gitconfig macos/gitconfig
link .bashrc macos/bashrc
link .bash_profile macos/bash_profile
link .grc .grc
link .chunkwmrc macos/chunkwmrc
link .shkdrc macos/skhdrc

# SSH
rm -rf ~/.ssh
ln -s "${DROPBOX}"/System/ssh ~/.ssh
chmod 0700 ~/.ssh
chmod 0600 ~/.ssh/id_rsa*

# AWS Credentials
rm -rf ~/.aws
ln -s "${DROPBOX}"/System/aws ~/.aws
chmod 0700 ~/.aws
chmod 0600 ~/.aws/*

# Kitty
mkdir -p ~/Library/Preferences/kitty
link Library/Preferences/kitty/kitty.conf kitty.conf

# XCode Themes
XCODE_THEMES=Library/Developer/Xcode/UserData/FontAndColorThemes
mkdir -p ~/$XCODE_THEMES
link $XCODE_THEMES/Meowgorithm.dvtcolortheme xcode/Meowgorithm.dvtcolortheme
link $XCODE_THEMES/MeowgorithmMorning.dvtcolortheme xcode/MeowgorithmMorning.dvtcolortheme

echo
echo Done.
echo
