#!/bin/bash

THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DROPBOX=$HOME/Soft\ Power\ Dropbox/Christian\ Rocha

function link() {
    rm -rf ~/$1
    ln -s $THISDIR/$2 ~/$1
}

mkdir -p $HOME/.config

link .gitignore gitignore
link .gemrc gemrc
link .eslintrc eslintrc
link .zshrc zshrc
link .tmux.conf tmux.conf
link .gitconfig macos/gitconfig
link .bashrc macos/bashrc
link .bash_profile macos/bash_profile
link .grc .grc
link .config/yabai/yabairc macos/yabairc
link .skhdrc macos/skhdrc
link .config/.floskell.json floskell.json
link .hindent.yaml hindent.yaml
link .config/fish config/fish

# SSH
rm -rf ~/.ssh
ln -s "${DROPBOX}"/System/ssh ~/.ssh
chmod 0700 ~/.ssh
chmod 0600 ~/.ssh/id_rsa*

# AWS Credentials
rm -rf ~/.aws
ln -s "${DROPBOX}"/System/aws ~/.aws
chmod 0700 ~/.aws
chmod 0600 ~/.aws/*

# Kitty
mkdir -p ~/.config/kitty
link .config/kitty/kitty.conf kitty.conf

# XCode Themes
XCODE_THEMES=Library/Developer/Xcode/UserData/FontAndColorThemes
mkdir -p ~/$XCODE_THEMES
link $XCODE_THEMES/Meowgorithm.dvtcolortheme xcode/Meowgorithm.dvtcolortheme
link $XCODE_THEMES/MeowgorithmMorning.dvtcolortheme xcode/MeowgorithmMorning.dvtcolortheme

echo
echo Done.
echo
