#!/bin/bash

THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ln -s $THISDIR/gitignore ~/.gitignore
ln -s $THISDIR/gemrc ~/.gemrc
ln -s $THISDIR/osx/bash_profile ~/.bash_profile
ln -s $THISDIR/osx/bashrc ~/.bashrc
ln -s $THISDIR/osx/gitconfig ~/.gitconfig

unset THISDIR
