#!/bin/bash

# Some system notes
#
# * X570 Aorus Master
# * AMD Ryzen 9 5950X 16-Core
# * NVIDIA GeForce RTX 3090
# * 64GB Ram
# * GC-Titan Ridge 2.0 for Thunderbolt support
# * LG Ultrafine 5K Thunderbolt display, Connected via the GC-Titan Ridge 2.0.
#   It has several features which are activated once Thunderbolt support is
#   enabled:
#     * Camera
#     * Speakers
#     * USB-C hub
#   The brightness controls are proprietary; see the script that installs
#   the LG Ultrafine brightness controls.

for f in ./voidlinux/setup/*; do
    if [ ! -f $d ]; then
        continue
    fi
    bash "$f" || break
    printf '\n%s finished.\n\n' $(basename $f)
    read -n 1 -s -r -p "Press any key to continue..."
    printf '\n'
done
