#!/bin/bash

sudo xbps-install -Sy void-repo-nonfree
sudo xbps-install -Sy

sudo xbps-install -Sy \
    base-devel vpm \
    ncurses ncurses-devel ncurses-libtinfo-libs ncurses-libtinfo-devel \
    gcc6 gmp gmp-devel \
    go nodejs yarn ruby python python3-devel \
    xorg-minimal xorg-input-drivers setxkbmap \
    nvidia nvidia-libs nvidia-opencl nvidia-gtklibs nvidia-dkms nv-codec-headers \
    noto-fonts-ttf noto-fonts-ttf-extra noto-fonts-cjk noto-fonts-emoji \
    dejavu-fonts-ttf ttf-ubuntu-font-family \
    ctags curl wget bash-completion ripgrep jq \
    sx xfce4 picom i3-gaps i3status \
    rofi kitty firefox

# Vim
git clone https://github.com/vim/vim.git
cd vim
./configure --with-features=huge \
    --enable-multibyte \
    --enable-rubyinterp=yes \
    --enable-python3interp=yes \
    --with-python3-config-dir=/usr/lib64/python3.9/config-3.9m-x86_64-linux-gnu \
    --enable-perlinterp=yes \
    --enable-luainterp=yes \
    --enable-cscope \
    --prefix=/usr/local
make -j16
sudo make install
cd ..
rm -rf vim

# GHCUP
mkdir -p "$HOME/.ghcup/bin"
curl https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup --output "$HOME/.ghcup/bin/ghcup"
chmod u+x "$HOME/.ghcup/bin/ghcup"

# Z
git clone https://github.com/rupa/z.git
sudo mv ./z/z.sh /usr/local/bin/
sudo mkdir -p /usr/local/man/man1
sudo mv ./z/z.1 /usr/local/man/man1/
rm -rf z

# Bonus Fonts
mkdir -p "$HOME/.fonts"
curl https://media.rocha.is/fonts.tgz.charmed | charm decrypt | tar zvxf - -C "$HOME/.fonts"
fc-cache -v

# Make Thunderbolt USB "just work"
# Note that on Arch the path here would be /etc/udev/rules.d/99-removable.rules
sudo sh -c $'echo \'ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"\' > /usr/lib/udev/rules.d/99-removable-rules'

mkdir -p "$HOME/.go"
