#!/usr/bin/env bash

# Figure out which OS/Distro we're on
case "$OSTYPE" in
    darwin*)
        printf "darwin" ;;

    linux*)
        if [[ -f "/etc/issue" ]]; then
            issue=$(cat /etc/issue)
            if   [[ $issue =~ "Void"   ]]; then printf "void"
            elif [[ $issue =~ "Arch"   ]]; then printf "arch"
            elif [[ $issue =~ "Debian" ]]; then printf "debian"
            else printf "linux"
            fi
        fi ;;
esac
