[wallpaper]
directory = "/home/christian/Downloads"
fill_mode = "span"

[wallpaper.default]
path = "/home/christian/.config/noctalia/bbq.png"

[wallpaper.last]
path = "/home/christian/.config/noctalia/bbq.png"

[wallpaper.monitors.DP-1]
path = "/home/christian/.config/noctalia/bbq.png"

[widget.workspaces]
focused_color = "#BFBCC8"
occupied_color = "#858392"
empty_color = "#605F6B"

[shell.screenshot]
save_to_file = true
copy_to_clipboard = true

[theme.templates.user.firefox_chrome]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/firefox/userChrome.css"
output_path = "$XDG_CACHE_HOME/noctalia/firefox/userChrome.css"
post_hook = "bash '{{ config_dir }}/templates/firefox/apply.sh'"

[theme.templates.user.firefox_content]
input_path = "$XDG_CONFIG_HOME/noctalia/templates/firefox/userContent.css"
output_path = "$XDG_CACHE_HOME/noctalia/firefox/userContent.css"
post_hook = "bash '{{ config_dir }}/templates/firefox/apply.sh'"
