#!/bin/bash
THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function link() {
    rm -rf ~/$2
    ln -s $THISDIR/$1 ~/$2
}

mkdir -p ~/.config

link bin .bin
link profile .profile
link bash_profile .bash_profile
link bashrc .bashrc
link gitconfig .gitconfig
link Xresources .Xresources
link config/sx .config/sx
link config/picom.conf .config/picom.conf
link config/kitty .config/kitty
link config/rofi .config/rofi
link ../floskell.json .config/.floskell.json
