[tools]
ffmpeg = "latest"
fzf = "latest"
glow = "latest"
gum = "latest"
helix = "latest"
hivemind = "latest"
imagemagick = "latest"
jj = "latest"
neovim = "latest"
pandoc = "latest"
prettier = "latest"
ripgrep = "latest"
rtk = "latest"
ruff = "latest"
rust = "latest"
rust-analyzer = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
svgo = "latest"
taplo = "latest"
tmux = "latest"
tombi = "latest"
ty = "latest"
zellij = "latest"
