[settings]
experimental = true

[tools]
ffmpeg = "latest"
fzf = "latest"
glow = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/nametake/golangci-lint-langserver" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
golangci-lint = "latest"
gum = "latest"
helix = "latest"
hivemind = "latest"
imagemagick = "latest"
jj = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "lts"
pandoc = "latest"
pitchfork = "latest"
prettier = "latest"
python = "3.13"
ripgrep = "latest"
rtk = "latest"
ruff = "latest"
rust = "latest"
rust-analyzer = "latest"
semgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
svgo = "latest"
taplo = "latest"
task = "latest"
tmux = "latest"
tombi = "latest"
ty = "latest"
zellij = "latest"
