[settings]
experimental = true

[daemons.postgres]
preset = "postgres"
version = "latest"

[tools]
ffmpeg = "latest"
fzf = "latest"
glow = "latest"
gum = "latest"
helix = "latest"
hivemind = "latest"
imagemagick = "latest"
jj = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "lts"
pandoc = "latest"
pitchfork = "latest"
prettier = "latest"
python = "3.13"
ripgrep = "latest"
rtk = "latest"
ruff = "latest"
rust = "latest"
rust-analyzer = "latest"
semgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
svgo = "latest"
taplo = "latest"
task = "latest"
tmux = "latest"
tombi = "latest"
ty = "latest"
zellij = "latest"
