#!/bin/bash

other_packages=""

while true; do
    read -p "Is this a VM? [yn] " yn
    case $yn in
        [yY]* )
            other_packages="xf86-video-vmware open-vm-tools"
            break;;
        [nN]* )
            other_packages="nvidia nvidia-libs nvidia-opencl nvidia-gtklibs nvidia-dkms nv-codec-headers"
            break;;
        * )
            printf "Please enter yes or no\n";;
    esac
done

sudo xbps-install -Sy void-repo-nonfree
sudo xbps-install -Sy
sudo xbps-install -Sy \
    base-devel vpm gcc6 cmake gmp gmp-devel gcc-ada libusb \
    ncurses ncurses-devel ncurses-libtinfo-libs ncurses-libtinfo-devel \
    zlib-devel libusb-devel alsa-lib-devel \
    chrony alsa-utils apulse pulsemixer bluez bolt \
    git gnupg gnupg2 nix \
    bsdtar psmisc ctags curl wget bash-completion ripgrep jq direnv fzf \
    moreutils \
    go rust cargo nodejs yarn ruby python python3-devel shellcheck \
    noto-fonts-ttf noto-fonts-ttf-extra noto-fonts-cjk noto-fonts-emoji \
    dejavu-fonts-ttf ttf-ubuntu-font-family font-material-design-icons-ttf \
    mesa xorg-minimal xorg-input-drivers setxkbmap xrandr xrdb \
    libX11-devel libXrandr-devel libXScrnSaver-devel libXinerama-devel \
    libXpm-devel libXft libXft-devel \
    xclip xset xsel xseticon xsetmode xsetpointer xsetroot xsettingsd \
    xdg-user-dirs \
    adwaita-icon-theme \
    sx picom feh slop gcolor2 \
    gthumb rofi kitty firefox \
    $other_packages
