#!/bin/bash

printf "Setting up xbps-src...\n\n"

mkdir -p "$HOME/src"
cd "$HOME/src"

git clone git://github.com/void-linux/void-packages.git
cd void-packages
./xbps-src binary-bootstrap
echo XBPS_ALLOW_RESTRICTED=yes >> etc/conf
