#!/bin/bash

printf "Installing Vim...\n\n"

mkdir -p "$HOME/src"
cd "$HOME/src"

git clone https://github.com/vim/vim.git
cd vim
./configure --with-features=huge \
    --enable-multibyte \
    --enable-rubyinterp=yes \
    --enable-python3interp=yes \
    --with-python3-config-dir=/usr/lib64/python3.9/config-3.9m-x86_64-linux-gnu \
    --enable-perlinterp=yes \
    --enable-luainterp=yes \
    --enable-cscope \
    --prefix=/usr/local
make -j16
sudo make install
cd ..
rm -rf vim
