# Hyprlock configuration
# https://github.com/hyprwm/hyprlock

general {
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 12
    noise = 0.01
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(33ccffee)
    inner_color = rgba(1a1a1aee)
    font_color = rgba(ffffffee)
    placeholder_text = <i>Password</i>
    hide_input = false
    check_color = rgba(00ff99ee)
    fail_color = rgba(ff5555ee)
    fail_text = <i>$FAIL</i>
    capslock_color = rgba(ffff55ee)
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font = false

    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(ffffffee)
    font_size = 80
    font_family = IBM Plex Mono

    position = 0, -250
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi, $USER
    color = rgba(ffffffee)
    font_size = 24
    font_family = IBM Plex Mono

    position = 0, -30
    halign = center
    valign = center
}
