# Hypridle configuration
# https://github.com/hyprwm/hypridle

general {
    lock_cmd = hyprlock
    unlock_cmd =
    before_sleep_cmd = hyprlock
    after_sleep_cmd =
    ignore_dbus_inhibit = false
}

# Lock before sleep
listener {
    timeout = 0
    on-timeout =
}

# Lock on lid close (handled by systemd-logind)
listener {
    timeout = 0
    on-timeout =
    on-resume =
}
