#!/bin/bash

THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function link() {
    rm -rf "${HOME:?}/$1"
    ln -s "$THISDIR/$2" "$HOME/$1"
}

mkdir -p "$HOME/.config/{bspwm,panel,sxhkd,kitty}"

link .Xresources Xresources
link .xinitrc xinitrc
link .gitconfig gitconfig

# ghcup
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
