#! /bin/sh

# These could be moved to ~/.profile
PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=52
#PANEL_FONT="-*-fixed-*-*-*-*-10-*-*-*-*-*-*-*"
#PANEL_FONT="SF Mono:weight=Medium:pixelsize=12:antialias=true:hinting=slight"
PANEL_FONT="Deja Vu Sans Mono:pixelsize=24:antialias=true:hinting=slight"
PANEL_WM_NAME=bspwm_panel

panel_bar=~/.config/panel/panel_bar
panel_colors=~/.config/panel/panel_colors

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

#monitor_width=$(bspc query -T -m | grep -oE "width\":[0-9]{2,6}" | head -n 1 | grep -oE "[0-9]{2,6}")
#monitor_height=$(bspc query -T -m | grep -oE "height\":[0-9]{2,6}" | head -n 1 | grep -oE "[0-9]{2,6}")

bspc config top_padding 0
bspc config bottom_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &
xtitle -sf 'T%s\n' > "$PANEL_FIFO" &
#clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &
date '+S%a %H:%M' > "$PANEL_FIFO" &

. "$panel_colors"

"$panel_bar" < "$PANEL_FIFO" | lemonbar -b -a 32 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
