#!/bin/env bash

# Get user-installed xbps packages and strip version info.
#
# We could also list all installed packages with:
#    xbps-query -l | awk '{ print $2 }' | xargs -n1 xbps-uhelper getpkgname | fmt

xbps-query -m \
    | xargs -n1 xbps-uhelper getpkgname \
    | fmt \
    | sed -r 's/(slack-desktop|discord)//'
