#!/usr/bin/env bash

thisdir=$(dirname "$(realpath ~/.bashrc)")
os="$($thisdir/utils/which-os)"

# Install package
sudo xbps-install -S $1

# Update list of installed packages
if [[ $? == 0 ]]; then
    echo $("$thisdir/utils/get-xbps-packages") | fmt > "$thisdir/packages.txt"
fi
