#!/usr/bin/env bash

opts="$(
    cat <<EOF
Air:go install -v github.com/air-verse/air@latest
Charmtone:go install -v github.com/charmbracelet/x/examples/charmtone@main
GHCup:install-ghcup
Hivemind:go install -v github.com/DarthSim/hivemind@latest
Task:go install -v github.com/go-task/task/v3/cmd/task@latest
Templ:go install -v github.com/a-h/templ/cmd/templ@latest
V:install-v
z.lua:install-z.lua
EOF
)"

eval "$(
    printf "%s" "$opts" |
        gum choose \
            --header="What would you like to install?" \
            --label-delimiter=":"
)"
