#!/usr/bin/env bash

opts="$(
    cat <<EOF
Charmtone:go install github.com/charmbracelet/x/examples/charmtone@main
Task:go install github.com/go-task/task/v3/cmd/task@latest
Air:go install github.com/air-verse/air@latest
EOF
)"

eval "$(
    printf "%s" "$opts" |
        gum choose \
            --header="What would you like to install?" \
            --label-delimiter=":"
)"
