#!/usr/bin/env bash

which_os() {
    case "$OSTYPE" in
        darwin*)
            printf "darwin" ;;

        linux*)
            if [[ -f "/etc/issue" ]]; then
                issue=$(cat /etc/issue)
                if   [[ $issue =~ "NixOS"  ]]; then printf "nixos"
                elif [[ $issue =~ "Void"   ]]; then printf "void"
                elif [[ $issue =~ "Arch"   ]]; then printf "arch"
                elif [[ $issue =~ "Debian" ]]; then printf "debian"
                else printf "linux"
                fi
            fi ;;
    esac
    printf ""
}

command_exists() {
    if command -v "$1" &> /dev/null
    then
        printf 1
        return
    fi
    printf 0
}

commands_exist() {
    for arg in "$@"; do
        if [[ ! command_exists != "$arg" ]]; then
            printf '%s' "$arg"
        fi
    done
    printf ""
}

#shellcheck disable=1090
decryptAndSource() {
    command -v gpg > /dev/null 2>&1 && \
        source <(gpg --decrypt <<< "$1" 2> /dev/null)
}

gitdiff() {
    if [[ $(which_os) == darwin ]]; then
        opendiff
    else
        vimdiff
    fi
}

remove_headerbar() {
    case "$OSTYPE" in
        linux*) xprop -format _MOTIF_WM_HINTS 32c -set _MOTIF_WM_HINTS 2 ;;
        *) return ;;
    esac
}
