# include .profile if it exists
[[ -f ~/.profile ]] && . ~/.profile

# include .bashrc if it exists
[[ -f ~/.bashrc ]] && . ~/.bashrc

# vim:syn=bash

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
[[ -f ~/.orbstack/shell/init.bash ]] && source ~/.orbstack/shell/init.bash
